# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/GitRepositories/CA_2018/test_env/test_env.cache/wt [current_project]
set_property parent.project_path F:/GitRepositories/CA_2018/test_env/test_env.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/GitRepositories/CA_2018/test_env/test_env.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  F:/GitRepositories/CA_2018/test_env/test_env.srcs/sources_1/new/mpg.vhd
  F:/GitRepositories/CA_2018/test_env/test_env.srcs/sources_1/new/display.vhd
  F:/GitRepositories/CA_2018/test_env/test_env.srcs/sources_1/new/test.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/GitRepositories/CA_2018/test_env/test_env.srcs/constrs_1/new/constr.xdc
set_property used_in_implementation false [get_files F:/GitRepositories/CA_2018/test_env/test_env.srcs/constrs_1/new/constr.xdc]


synth_design -top test -part xc7a35tcpg236-1


write_checkpoint -force -noxdef test.dcp

catch { report_utilization -file test_utilization_synth.rpt -pb test_utilization_synth.pb }
